enum ACTION_TYPES {
    SET_TRACKS = '@ORTALIO_PLAYER/SET_TRACKS',
    SELECT_TRACK = '@ORTALIO_PLAYER/SELECT_TRACK',
    UPDATE_SELECTED_TRACK = '@ORTALIO_PLAYER/UPDATE_SELECTED_TRACK',
    PLAY_PAUSE_SELECTED_TRACK = '@ORTALIO_PLAYER/PLAY_PAUSE_SELECTED_TRACK',
}
export default ACTION_TYPES;
